/**:
  ros__parameters:
    planning_pipelines:
      pipeline_names:
        - ompl
    ompl:
      planning_plugins:
        - ompl_interface/OMPLPlanner
      request_adapters:
        - default_planning_request_adapters/ResolveConstraintFrames
        - default_planning_request_adapters/ValidateWorkspaceBounds
        - default_planning_request_adapters/CheckStartStateBounds
        - default_planning_request_adapters/CheckStartStateCollision
      start_state_max_bounds_error: 0.1
      arm:
        default_planner_config: ompl_rrtc
        planner_configs:
          - ompl_rrtc
        projection_evaluator: joints(joint_1,joint_2)
        longest_valid_segment_fraction: 0.05
        max_planning_time: 5.0
        max_iterations: 500
        max_solutions: 10
        min_solution_fraction: 0.9
        num_samples: 100
        num_waypoints: 10
        simplified_solutions: true
      arm_gripper:
        default_planner_config: ompl_rrtc
        planner_configs:
          - ompl_rrtc
        projection_evaluator: joints(joint_1,joint_2)
        longest_valid_segment_fraction: 0.05
        max_planning_time: 5.0
        max_iterations: 500
        max_solutions: 10
        min_solution_fraction: 0.9
        num_samples: 100
        num_waypoints: 10
        simplified_solutions: true
      planner_configs:
        ompl_rrtc:
          type: geometric::RRTConnect
          range: 0.4
